Blogpost agnes
Edirom/ViFE-website pull request #50
Opened 2024-10-04 12:21 UTC by aseipelt

Here is my blogpost for the ViFE website. please check out if the image fits because I cannot see it.

2024-10-06 15:13 UTC, riedde requested changes
Sehr schön! Ich habe ein paar Tippfehler gefunden und wenige Vorschläge zur Umformulierung gemacht. (Ich konnte das leider nicht als Suggestion machen, geht scheinbar nicht bei Text.)

2024-10-06 15:13 UTC, riedde commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +excerpt: "ViFE-Mitglied Agnes stellt sich vor und berichtet von ihrem Weg zum ViFE, ihre Arbeit für Beethovens Werkstatt und über ihr Dissertationsprojekt"
ViFE-Mitglied Agnes stellt sich vor und berichtet von ihrem Weg zum ViFE, über ihre Arbeit für Beethovens Werkstatt und ihr Dissertationsprojekt

2024-10-06 15:13 UTC, riedde commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +excerpt: "ViFE-Mitglied Agnes stellt sich vor und berichtet von ihrem Weg zum ViFE, ihre Arbeit für Beethovens Werkstatt und über ihr Dissertationsprojekt"
Ich habe das "über" vorgezogen, damit es grammatikalisch stimmt. Ist nur ein Vorschlag!

2024-10-06 15:13 UTC, riedde commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Mein Name ist Agnes Seipelt und ich bin seit 2017 offiziell Teil des ViFE. 2009 habe ich in Detmold/Paderborn den Zwei-Fach Bachelor mit den Fächern Musikwissenschaft und Romanistik begonnen, den ich
Letzter Satz: "erschien" statt "erschienen" + Am ende dazu: "erreichbar/verfügbar ist."

2024-10-06 15:13 UTC, riedde commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Im Masterstudium Musikwissenschaft habe ich den Professionalisierungsbereich „Digitale Edition“ gewählt, wodurch ich durch Seminare und Vorlesungen zu Theorie und Methoden Digitaler Musikwissenschaft
Ich würde SHK ausschreiben.

2024-10-06 15:13 UTC, riedde commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Thematisch habe ich mich schon immer am meisten für die Codierung und Modellierung von Musik mit MEI interessiert. In meiner Masterarbeit konnte ich das in die Praxis umsetzten und habe mich mit dem
"die Praxis umsetzten" -> "umsetzen" (Typo)

2024-10-06 15:13 UTC, riedde commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Noch in meiner Zeit im Bruckner Projekt wurde ich zu einem Arbeitstreffen vom Projekt Beethovens Werkstatt eingeladen, das das Konzept der Harmonischen Analyse im Ramen des 2 Moduls aufgreifen wollte
"im Ramen" -> "im Rahmen"

2024-10-06 15:13 UTC, riedde commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Seit 2019 bin ich nun Teil des Detmolder Teams von Beethovens Werkstatt. Das Projekt erforscht kompositorische Denk- und Arbeitsprozesse am Beispiel von Beethoven, wobei die Methoden der genetischen
"Aufgaben wie das Nachdenken über und Konzipieren von unseren Datenmodellen"
Vorschlag: "Aufgaben wie das Nachdenken über und die Konzeption unserer Datenmodelle"

2024-10-07 15:28 UTC, peterstadler requested changes
Nur zwei Kleinigkeiten  – vielen Dank für den schönen Text!

2024-10-07 15:28 UTC, peterstadler commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Seit 2019 bin ich nun Teil des detmolder Teams von Beethovens Werkstatt. Das Projekt erforscht kompositorische Denk- und Arbeitsprozesse am Beispiel von Beethoven, wobei die Methoden der genetischen
```suggestion
Seit 2019 bin ich nun Teil des Detmolder Teams von Beethovens Werkstatt. Das Projekt erforscht kompositorische Denk- und Arbeitsprozesse am Beispiel von Beethoven, wobei die Methoden der genetischen Textkritik weiterentwickelt und gleichzeitig digitale Formen zur Präsentation der Forschungsergebnisse geschaffen werden. Die ursprüngliche, konzeptuelle Aufteilung der Arbeitsstellen in „philologisch“ (Arbeitsstelle Bonn) und „digital/technisch“ (Arbeitsstelle Detmold) ist seit Projektbeginn auf natürliche Weise immer mehr aufgeweicht worden. So werden die, natürlich je nach Modul immer etwas anders gelagerten, Aufgaben wie das Nachdenken über und die Konzeption unserer Datenmodelle, das Anfertigen von Musikcodierungen mit MEI, philologische Arbeiten wie das Transkribieren von Skizzen und anderen Handschriften, das Konzipieren von Transkriptions- und Codierungsrichtlinien, das Transformieren von Codierungen sowie Korrekturlesearbeiten und das Verfassen von begleitenden Texten von allen MitarbeiterInnen meist gleichermaßen übernommen. 
```

2024-10-07 15:28 UTC, peterstadler commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Thematisch habe ich mich schon immer am meisten für die Codierung und Modellierung von Musik mit MEI interessiert. In meiner Masterarbeit konnte ich das in die Praxis umsetzen und habe mich mit dem M
Gibt es einen Link zur MEC? Vielleicht sogar zu Deinem Abstract oder den Proceedings? Das würde ich hier noch verlinken!

2024-10-08 12:10 UTC, obertsalome reviewed
Manche Formulierungen fand ich etwas umgangssprachlich und habe daher Änderungsvorschläge gemacht. Wenn du möchtest, könntest du noch Links zur WeGA und dem Hoftheater einfügen – auch da "Hoftheater-Projekt" ja nicht der offizielle Projektname ist ;)

2024-10-08 12:10 UTC, obertsalome commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +<figurecaption>Auf der GfM-Jahrestagung in Saarbrücken im Oktober 2023, hochkonzentriert. Normalerweise schaue ich netter. Foto: Ran Mo</figurecaption>
```suggestion
<figurecaption>Bei der GfM-Jahrestagung in Saarbrücken im Oktober 2023, hochkonzentriert. Normalerweise schaue ich netter. Foto: Ran Mo</figurecaption>
```

2024-10-08 12:10 UTC, obertsalome commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Im Masterstudium Musikwissenschaft habe ich den Professionalisierungsbereich „Digitale Edition“ gewählt, wodurch ich durch Seminare und Vorlesungen zu Theorie und Methoden Digitaler Musikwissenschaft
```suggestion
Im Masterstudium Musikwissenschaft habe ich den Professionalisierungsbereich „Digitale Edition“ gewählt, wo ich durch Seminare und Vorlesungen zu Theorie und Methoden Digitaler Musikwissenschaft und Informatik einen Ein- und Überblick über das Feld bekam. Nebenbei habe ich durch die Arbeit als Studentische Hilfskraft in Forschungsprojekten wie der Weber-Gesamtausgabe und dem Hoftheater-Projekt aber die realen Anwendungsfälle und die tägliche Praxis erlebt, was sehr wertvoll war, nicht zu sprechen von den Kontakten zu einigen ViFEn.
```

2024-10-08 12:10 UTC, obertsalome commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Thematisch habe ich mich schon immer am meisten für die Codierung und Modellierung von Musik mit MEI interessiert. In meiner Masterarbeit konnte ich das in die Praxis umsetzen und habe mich mit dem M
```suggestion
Thematisch habe ich mich schon immer am meisten für die Codierung und Modellierung von Musik mit MEI interessiert. In meiner Masterarbeit konnte ich das in die Praxis umsetzen und habe mich mit dem Manuskript zur Erstaufführung von Webers *Freischütz* 1821 in Wien beschäftigt, das zensurbedingten, externen Eingriffen unterlag. Für diese Veränderungen, die teils inhaltlicher und teils materieller Natur sind, habe ich verschiedene Konzepte für die Codierung und Modellierung der Daten diskutiert und bin dadurch bereits auf die Konzepte von Beethovens Werkstatt aufmerksam geworden. Erfreulicherweise konnte ich meine Abschlussarbeit direkt auf der [Music Encoding Conference 2016 in Montréal](http://doi.org/10.15463/music-1) vorstellen.
```

2024-10-08 12:10 UTC, obertsalome commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Kurz nach Abschluss meines Masterstudiums habe ich bei Andreas Münzmay als Mitarbeiterin angefangen und zeitgleich in dem zweijährigen Forschungsprojekt ["Digitale Musikanalyse mit den Techniken der
```suggestion
Kurz nach Abschluss meines Masterstudiums habe ich bei Andreas Münzmay als Wissenschaftliche Mitarbeiterin angefangen, zu arbeiten und zeitgleich in dem zweijährigen Forschungsprojekt ["Digitale Musikanalyse mit den Techniken der Music Encoding Initiative (MEI) am Beispiel der Kompositionsstudien Anton Bruckners“](http://www.bruckner-online.at/?page_id=1570) an der Österreichischen Akademie der Wissenschaften. In diesem Projekt haben wir das Studienbuch von Anton Bruckner, das er bei seiner Lehrzeit bei Otto Kitzler anlegte, vollständig in MEI codiert und in einem Viewer in einer synoptischen Ansicht bereitgestellt. Die zahlreichen kurzen harmonischen Studien, Kadenzen und Modulationen dienten zudem als Spielwiese für die Konzeption einer (teil)automatischen harmonischen Analyse der Musik mittels XSL-Transformationen.
```

2024-10-08 12:10 UTC, obertsalome commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Noch in meiner Zeit im Bruckner Projekt wurde ich zu einem Arbeitstreffen vom Projekt Beethovens Werkstatt eingeladen, das das Konzept der Harmonischen Analyse im Rahmen des 2 Moduls aufgreifen wollt
```suggestion
Noch in meiner Zeit im Bruckner Projekt wurde ich zu einem Arbeitstreffen vom Projekt Beethovens Werkstatt eingeladen, das das Konzept der harmonischen Analyse im Rahmen des zweiten Moduls aufgreifen wollte. Nach Ende des Bruckner-Projekts konnte ich dann glücklicherweise direkt bei Beethovens Werkstatt anfangen und habe die harmonische Analyse (mit einigen Anpassungen und Verbesserungen) mit Hilfe von Johannes Kepper als eine der Perspektiven in der Vide-App von [Modul 2](https://beethovens-werkstatt.de/modul-2/) implementiert. 
```

2024-10-08 12:10 UTC, obertsalome commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +Daneben beschäftige ich mich im Rahmen meiner Dissertation mit der Bagatelle Nr. 6 aus Op. 126 von Beethoven. Anknüpfend an Konzepte aus der „Werkstatt“ möchte ich eine genetische Edition der Bagatel
In diesem (letzten) Absatz müsstest du dich entscheiden, ob du Werkstatt mit oder ohne Anführungszeichen schreibst.

2024-10-09 14:55 UTC, riedde approved these changes
If the one suggestion is accapted, this is approved :)

2024-10-09 14:55 UTC, riedde commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +<img src="{{ '/assets/blog/2024-10-07/agnes.JPG' | relative_url }}" alt="Agnes Seipelt" style="height: 400px"/>
```suggestion
<img src="{{ '/assets/blog/2024-10-10/agnes.JPG' | relative_url }}" alt="Agnes Seipelt" style="height: 400px"/>
<br/>
```

2024-10-09 14:55 UTC, riedde commented on _posts/2024-10-10-Vorstellung-Agnes-Seipelt.md
> +<img src="{{ '/assets/blog/2024-10-07/agnes.JPG' | relative_url }}" alt="Agnes Seipelt" style="height: 400px"/>
typo in file path. the br is a quick fix for the position of the caption

2024-10-10 05:57 UTC, peterstadler approved these changes

2024-10-10 05:57 UTC, merged